export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || (typeof window !== 'undefined' ? window.location.origin + '/api' : 'http://localhost:5000/api');

export const INTEREST_TYPES = [
  { id: 'adventure', label: 'Adventure', emoji: '🏔️', description: 'Trekking, rafting, paragliding & more' },
  { id: 'temples', label: 'Temples', emoji: '🛕', description: 'Ancient temples & spiritual journeys' },
  { id: 'historical', label: 'Historical', emoji: '🏰', description: 'Forts, palaces & heritage walks' },
  { id: 'beaches', label: 'Beaches', emoji: '🌊', description: 'Sun, sand & coastal beauty' },
  { id: 'culture', label: 'Culture & Fairs', emoji: '🎭', description: 'Local traditions & vibrant fairs' },
  { id: 'nature', label: 'Nature', emoji: '🌿', description: 'Wildlife, forests & serene landscapes' },
  { id: 'food', label: 'Food Tourism', emoji: '🍛', description: 'Culinary trails & street food' },
  { id: 'festivals', label: 'Festivals', emoji: '🎪', description: 'Experience India\'s grand celebrations' },
];

export const INDIAN_STATES = [
  {
    id: 'rajasthan',
    name: 'Rajasthan',
    heroImage: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&h=500&fit=crop',
    bestSeason: 'October – March',
    tags: ['historical', 'culture', 'food'],
    avgBudgetPerDay: 3500,
    highlights: ['Jaipur Pink City', 'Thar Desert Safari', 'Udaipur Lakes', 'Jaisalmer Fort'],
    crowdLevel: 'High',
  },
  {
    id: 'kerala',
    name: 'Kerala',
    heroImage: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&h=500&fit=crop',
    bestSeason: 'September – March',
    tags: ['nature', 'beaches', 'food'],
    avgBudgetPerDay: 3000,
    highlights: ['Alleppey Backwaters', 'Munnar Tea Gardens', 'Kovalam Beach', 'Wayanad Wildlife'],
    crowdLevel: 'Medium',
  },
  {
    id: 'himachal',
    name: 'Himachal Pradesh',
    heroImage: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&h=500&fit=crop',
    bestSeason: 'March – June',
    tags: ['adventure', 'nature', 'temples'],
    avgBudgetPerDay: 2500,
    highlights: ['Manali Snow', 'Shimla Ridge', 'Spiti Valley', 'Dharamshala Monastery'],
    crowdLevel: 'Medium',
  },
  {
    id: 'goa',
    name: 'Goa',
    heroImage: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&h=500&fit=crop',
    bestSeason: 'November – February',
    tags: ['beaches', 'food', 'culture'],
    avgBudgetPerDay: 4000,
    highlights: ['Baga Beach', 'Old Goa Churches', 'Dudhsagar Falls', 'Night Markets'],
    crowdLevel: 'High',
  },
  {
    id: 'tamilnadu',
    name: 'Tamil Nadu',
    heroImage: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&h=500&fit=crop',
    bestSeason: 'November – February',
    tags: ['temples', 'historical', 'culture'],
    avgBudgetPerDay: 2500,
    highlights: ['Meenakshi Temple', 'Mahabalipuram', 'Ooty Hills', 'Chettinad Cuisine'],
    crowdLevel: 'Medium',
  },
  {
    id: 'uttarakhand',
    name: 'Uttarakhand',
    heroImage: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=800&h=500&fit=crop',
    bestSeason: 'March – June',
    tags: ['adventure', 'temples', 'nature'],
    avgBudgetPerDay: 2800,
    highlights: ['Rishikesh Rafting', 'Haridwar Ganga Aarti', 'Valley of Flowers', 'Nainital Lake'],
    crowdLevel: 'Medium',
  },
  {
    id: 'madhyapradesh',
    name: 'Madhya Pradesh',
    heroImage: 'https://images.unsplash.com/photo-1590077428593-a55bb07c4665?w=800&h=500&fit=crop',
    bestSeason: 'October – March',
    tags: ['historical', 'nature', 'temples'],
    avgBudgetPerDay: 2200,
    highlights: ['Khajuraho Temples', 'Bandhavgarh Tigers', 'Sanchi Stupa', 'Pachmarhi Hills'],
    crowdLevel: 'Low',
  },
  {
    id: 'odisha',
    name: 'Odisha',
    heroImage: 'https://images.unsplash.com/photo-1621427642442-20e4d4f641bb?w=800&h=500&fit=crop',
    bestSeason: 'October – March',
    tags: ['temples', 'culture', 'beaches'],
    avgBudgetPerDay: 2000,
    highlights: ['Jagannath Temple', 'Konark Sun Temple', 'Chilika Lake', 'Tribal Villages'],
    crowdLevel: 'Low',
  },
  {
    id: 'assam',
    name: 'Assam',
    heroImage: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=500&fit=crop',
    bestSeason: 'October – April',
    tags: ['nature', 'culture', 'food'],
    avgBudgetPerDay: 2000,
    highlights: ['Kaziranga Rhinos', 'Majuli Island', 'Tea Plantations', 'Kamakhya Temple'],
    crowdLevel: 'Low',
  },
  {
    id: 'gujarat',
    name: 'Gujarat',
    heroImage: 'https://images.unsplash.com/photo-1609766857041-ed402ea8069a?w=800&h=500&fit=crop',
    bestSeason: 'October – March',
    tags: ['culture', 'historical', 'festivals'],
    avgBudgetPerDay: 2500,
    highlights: ['Rann of Kutch', 'Gir Lions', 'Somnath Temple', 'Ahmedabad Heritage'],
    crowdLevel: 'Medium',
  },
];

export const FESTIVALS_2025 = [
  { id: 'f1', name: 'Pushkar Mela', state: 'Rajasthan', startDate: '2025-11-05', endDate: '2025-11-13', description: 'World-famous camel fair with folk performances and trading.', type: 'fair', crowdExpected: 'Very High' },
  { id: 'f2', name: 'Onam', state: 'Kerala', startDate: '2025-09-05', endDate: '2025-09-15', description: 'Harvest festival with boat races, pookalam, and Onam Sadya.', type: 'cultural', crowdExpected: 'High' },
  { id: 'f3', name: 'Hemis Festival', state: 'Ladakh', startDate: '2025-06-27', endDate: '2025-06-28', description: 'Masked mystic dance festival at Hemis Monastery.', type: 'religious', crowdExpected: 'Medium' },
  { id: 'f4', name: 'Hornbill Festival', state: 'Nagaland', startDate: '2025-12-01', endDate: '2025-12-10', description: 'Festival of Festivals showcasing Naga tribal culture.', type: 'cultural', crowdExpected: 'High' },
  { id: 'f5', name: 'Rann Utsav', state: 'Gujarat', startDate: '2025-11-01', endDate: '2026-02-28', description: 'Celebrating the white desert of Kutch with music and art.', type: 'cultural', crowdExpected: 'High' },
  { id: 'f6', name: 'Mysuru Dasara', state: 'Karnataka', startDate: '2025-09-22', endDate: '2025-10-02', description: '10-day royal celebration with illuminated palace and processions.', type: 'religious', crowdExpected: 'Very High' },
  { id: 'f7', name: 'Durga Puja', state: 'West Bengal', startDate: '2025-09-30', endDate: '2025-10-04', description: 'Grand worship of Goddess Durga with artistic pandals.', type: 'religious', crowdExpected: 'Very High' },
  { id: 'f8', name: 'Lohri', state: 'Punjab', startDate: '2025-01-13', endDate: '2025-01-13', description: 'Bonfire festival celebrating the winter harvest season.', type: 'cultural', crowdExpected: 'Medium' },
  { id: 'f9', name: 'Pongal', state: 'Tamil Nadu', startDate: '2025-01-14', endDate: '2025-01-17', description: 'Four-day harvest festival with Jallikattu and kolam art.', type: 'cultural', crowdExpected: 'High' },
  { id: 'f10', name: 'Bihu', state: 'Assam', startDate: '2025-04-14', endDate: '2025-04-20', description: 'Assamese new year with traditional dance and feasts.', type: 'cultural', crowdExpected: 'Medium' },
  { id: 'f11', name: 'Ganesh Chaturthi', state: 'Maharashtra', startDate: '2025-08-27', endDate: '2025-09-06', description: 'Grand celebration with massive Ganesh idols and immersion.', type: 'religious', crowdExpected: 'Very High' },
  { id: 'f12', name: 'Maha Shivaratri', state: 'Uttarakhand', startDate: '2025-02-26', endDate: '2025-02-26', description: 'Night-long worship of Lord Shiva at sacred temples.', type: 'religious', crowdExpected: 'High' },
  { id: 'f13', name: 'Holi', state: 'Uttar Pradesh', startDate: '2025-03-14', endDate: '2025-03-15', description: 'Festival of colors celebrating spring and good over evil.', type: 'religious', crowdExpected: 'Very High' },
  { id: 'f14', name: 'Diwali', state: 'Pan India', startDate: '2025-10-20', endDate: '2025-10-24', description: 'Festival of lights with fireworks, sweets, and celebrations.', type: 'religious', crowdExpected: 'Very High' },
  { id: 'f15', name: 'Kumbh Mela', state: 'Uttar Pradesh', startDate: '2025-01-13', endDate: '2025-02-26', description: 'Largest spiritual gathering on earth at Triveni Sangam.', type: 'religious', crowdExpected: 'Extreme' },
];

export const CROWD_LEVELS = {
  Low: { label: 'Low', color: '#4CAF50', percent: 25 },
  Medium: { label: 'Medium', color: '#FFC107', percent: 55 },
  High: { label: 'High', color: '#FF6B35', percent: 80 },
  'Very High': { label: 'Very High', color: '#FF4757', percent: 95 },
  Extreme: { label: 'Extreme', color: '#FF0000', percent: 100 },
};

export const BUDGET_RANGES = {
  budget: { label: 'Budget', min: 0, max: 2000, emoji: '💰' },
  moderate: { label: 'Moderate', min: 2000, max: 5000, emoji: '💵' },
  luxury: { label: 'Luxury', min: 5000, max: 15000, emoji: '💎' },
  ultra: { label: 'Ultra Luxury', min: 15000, max: 50000, emoji: '👑' },
};

export const MOCK_DESTINATIONS = [
  {
    id: 'd1',
    name: 'Jaipur - The Pink City',
    state: 'Rajasthan',
    category: 'historical',
    tags: ['historical', 'culture', 'food'],
    images: [
      'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=600&h=400&fit=crop',
    ],
    rating: 4.7,
    reviews: 12840,
    entryFee: '₹200 (Amer Fort), ₹50 (Hawa Mahal)',
    crowdLevel: 'High',
    weatherNow: { temp: 32, condition: 'Sunny', icon: '☀️' },
    nearbyHotels: [
      { name: 'Rambagh Palace', price: 25000, rating: 4.9 },
      { name: 'Hotel Pearl Palace', price: 1800, rating: 4.5 },
      { name: 'Zostel Jaipur', price: 600, rating: 4.2 },
    ],
    localFood: ['Dal Baati Churma', 'Laal Maas', 'Ghewar', 'Pyaaz Kachori'],
    travelTips: ['Visit Amer Fort early morning to avoid crowds', 'Hire a local guide for Jantar Mantar', 'Try the street food at Johari Bazaar'],
    lat: 26.9124,
    lng: 75.7873,
  },
  {
    id: 'd2',
    name: 'Alleppey Backwaters',
    state: 'Kerala',
    category: 'nature',
    tags: ['nature', 'beaches', 'food'],
    images: [
      'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=600&h=400&fit=crop',
    ],
    rating: 4.8,
    reviews: 9560,
    entryFee: '₹500 (Houseboat day trip)',
    crowdLevel: 'Medium',
    weatherNow: { temp: 28, condition: 'Partly Cloudy', icon: '⛅' },
    nearbyHotels: [
      { name: 'Kumarakom Lake Resort', price: 18000, rating: 4.8 },
      { name: 'Raheem Residency', price: 4500, rating: 4.4 },
      { name: 'Art Hostel', price: 800, rating: 4.1 },
    ],
    localFood: ['Kerala Fish Curry', 'Appam & Stew', 'Puttu & Kadala', 'Banana Chips'],
    travelTips: ['Book houseboats in advance during peak season', 'Visit Marari Beach nearby', 'Try toddy shop experiences'],
    lat: 9.4981,
    lng: 76.3388,
  },
  {
    id: 'd3',
    name: 'Manali',
    state: 'Himachal Pradesh',
    category: 'adventure',
    tags: ['adventure', 'nature'],
    images: [
      'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1585016495480-46bf3033dc65?w=600&h=400&fit=crop',
    ],
    rating: 4.6,
    reviews: 15200,
    entryFee: '₹Free (Rohtang Pass permit: ₹550)',
    crowdLevel: 'High',
    weatherNow: { temp: 12, condition: 'Snowy', icon: '❄️' },
    nearbyHotels: [
      { name: 'The Himalayan', price: 8500, rating: 4.7 },
      { name: 'Manu Allaya', price: 6000, rating: 4.5 },
      { name: 'Zostel Manali', price: 500, rating: 4.3 },
    ],
    localFood: ['Sidu', 'Trout Fish', 'Tibetan Momos', 'Dham'],
    travelTips: ['Get Rohtang permits online beforehand', 'Carry warm clothing year-round', 'Old Manali has the best cafes'],
    lat: 32.2432,
    lng: 77.1892,
  },
  {
    id: 'd4',
    name: 'Goa Beaches',
    state: 'Goa',
    category: 'beaches',
    tags: ['beaches', 'food', 'culture'],
    images: [
      'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&h=400&fit=crop',
    ],
    rating: 4.5,
    reviews: 21300,
    entryFee: '₹Free (most beaches)',
    crowdLevel: 'High',
    weatherNow: { temp: 31, condition: 'Sunny', icon: '☀️' },
    nearbyHotels: [
      { name: 'Taj Exotica', price: 22000, rating: 4.9 },
      { name: 'Acron Waterfront', price: 5500, rating: 4.4 },
      { name: 'Old Quarter Hostel', price: 700, rating: 4.2 },
    ],
    localFood: ['Fish Thali', 'Vindaloo', 'Bebinca', 'Prawn Balchão'],
    travelTips: ['North Goa for parties, South Goa for peace', 'Rent a scooter for best exploration', 'Visit on weekdays to avoid crowds'],
    lat: 15.2993,
    lng: 74.124,
  },
  {
    id: 'd5',
    name: 'Varanasi',
    state: 'Uttar Pradesh',
    category: 'temples',
    tags: ['temples', 'culture', 'food'],
    images: [
      'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=600&h=400&fit=crop',
    ],
    rating: 4.6,
    reviews: 18700,
    entryFee: '₹Free (ghats), ₹100 (Kashi Vishwanath)',
    crowdLevel: 'Very High',
    weatherNow: { temp: 35, condition: 'Hot', icon: '🔥' },
    nearbyHotels: [
      { name: 'BrijRama Palace', price: 12000, rating: 4.8 },
      { name: 'Hotel Ganges View', price: 3500, rating: 4.3 },
      { name: 'Moustache Hostel', price: 500, rating: 4.1 },
    ],
    localFood: ['Banarasi Paan', 'Kachori Sabzi', 'Malaiyo', 'Tamatar Chaat'],
    travelTips: ['Attend Ganga Aarti at Dashashwamedh Ghat', 'Sunrise boat ride is a must', 'Respect local customs at temples'],
    lat: 25.3176,
    lng: 82.9739,
  },
  {
    id: 'd6',
    name: 'Munnar',
    state: 'Kerala',
    category: 'nature',
    tags: ['nature', 'adventure'],
    images: [
      'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1571536802086-159f3cfe9e36?w=600&h=400&fit=crop',
    ],
    rating: 4.7,
    reviews: 8900,
    entryFee: '₹25 (Tea Museum), ₹35 (Eravikulam)',
    crowdLevel: 'Medium',
    weatherNow: { temp: 18, condition: 'Misty', icon: '🌫️' },
    nearbyHotels: [
      { name: 'Tea County', price: 5500, rating: 4.5 },
      { name: 'Windermere Estate', price: 9000, rating: 4.7 },
      { name: 'Hostel by the Lake', price: 600, rating: 4.0 },
    ],
    localFood: ['Kerala Porotta & Beef Fry', 'Fish Moilee', 'Banana Fritters', 'Tea & Cardamom Biscuits'],
    travelTips: ['Visit Eravikulam for Nilgiri Tahr sighting', 'Carry rain gear year-round', 'Don\'t miss the Top Station sunrise'],
    lat: 10.0889,
    lng: 77.0595,
  },
  {
    id: 'd7',
    name: 'Hampi',
    state: 'Karnataka',
    category: 'historical',
    tags: ['historical', 'culture'],
    images: [
      'https://images.unsplash.com/photo-1590077428593-a55bb07c4665?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1600100397608-93a2628e47ce?w=600&h=400&fit=crop',
    ],
    rating: 4.8,
    reviews: 7600,
    entryFee: '₹40 (Vijaya Vittala Complex)',
    crowdLevel: 'Low',
    weatherNow: { temp: 34, condition: 'Hot', icon: '☀️' },
    nearbyHotels: [
      { name: 'Evolve Back', price: 14000, rating: 4.8 },
      { name: 'Goan Corner', price: 1200, rating: 4.0 },
      { name: 'Sunny Guest House', price: 500, rating: 3.9 },
    ],
    localFood: ['Bisi Bele Bath', 'Ragi Mudde', 'South Indian Thali', 'Mango Lassi'],
    travelTips: ['Rent a bicycle to explore ruins', 'Visit Stone Chariot at sunrise', 'Cross river to Hippie Island for cafes'],
    lat: 15.335,
    lng: 76.4601,
  },
  {
    id: 'd8',
    name: 'Rishikesh',
    state: 'Uttarakhand',
    category: 'adventure',
    tags: ['adventure', 'temples'],
    images: [
      'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1588229959069-d87d7ee39a0e?w=600&h=400&fit=crop',
    ],
    rating: 4.6,
    reviews: 11200,
    entryFee: '₹Free (Laxman Jhula), ₹1500+ (Rafting)',
    crowdLevel: 'Medium',
    weatherNow: { temp: 22, condition: 'Clear', icon: '🌤️' },
    nearbyHotels: [
      { name: 'Aloha on the Ganges', price: 7500, rating: 4.6 },
      { name: 'Atali Ganga', price: 12000, rating: 4.8 },
      { name: 'Zostel Rishikesh', price: 500, rating: 4.3 },
    ],
    localFood: ['Aloo Puri', 'Chole Bhature', 'Banana Pancakes', 'Fresh Juice'],
    travelTips: ['Book rafting in advance for 16km route', 'Visit Beatles Ashram for unique experience', 'Attend evening aarti at Triveni Ghat'],
    lat: 30.0869,
    lng: 78.2676,
  },
  {
    id: 'd9',
    name: 'Rann of Kutch',
    state: 'Gujarat',
    category: 'culture',
    tags: ['culture', 'festivals'],
    images: [
      'https://images.unsplash.com/photo-1609766857041-ed402ea8069a?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?w=600&h=400&fit=crop',
    ],
    rating: 4.7,
    reviews: 6400,
    entryFee: '₹100 (White Desert entry)',
    crowdLevel: 'Medium',
    weatherNow: { temp: 28, condition: 'Clear', icon: '🌤️' },
    nearbyHotels: [
      { name: 'Rann Utsav Tent City', price: 8000, rating: 4.5 },
      { name: 'Shaam-e-Sarhad', price: 4000, rating: 4.3 },
      { name: 'Gateway Kutch', price: 3500, rating: 4.1 },
    ],
    localFood: ['Dabeli', 'Kutchi Kakdi Raita', 'Bajra Rotla', 'Mawa Cake'],
    travelTips: ['Visit during Rann Utsav (Nov-Feb) for the best experience', 'Full moon nights are magical on white salt', 'Book tent stays in advance'],
    lat: 23.7337,
    lng: 69.8597,
  },
  {
    id: 'd10',
    name: 'Darjeeling',
    state: 'West Bengal',
    category: 'nature',
    tags: ['nature', 'food'],
    images: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=600&h=400&fit=crop',
    ],
    rating: 4.5,
    reviews: 9800,
    entryFee: '₹Free (Tiger Hill sunrise: ₹30)',
    crowdLevel: 'Medium',
    weatherNow: { temp: 14, condition: 'Cloudy', icon: '☁️' },
    nearbyHotels: [
      { name: 'Mayfair Darjeeling', price: 9000, rating: 4.6 },
      { name: 'Windamere Hotel', price: 7000, rating: 4.5 },
      { name: 'Revolver Hostel', price: 600, rating: 4.2 },
    ],
    localFood: ['Darjeeling Tea', 'Thukpa', 'Momos', 'Sel Roti'],
    travelTips: ['Tiger Hill sunrise view of Kanchenjunga', 'Ride the UNESCO toy train', 'Visit Happy Valley Tea Estate'],
    lat: 27.0410,
    lng: 88.2663,
  },
  {
    id: 'd11',
    name: 'Udaipur',
    state: 'Rajasthan',
    category: 'historical',
    tags: ['historical', 'culture', 'food'],
    images: [
      'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1568495248636-6432b97bd949?w=600&h=400&fit=crop',
    ],
    rating: 4.8,
    reviews: 14300,
    entryFee: '₹300 (City Palace), ₹200 (Sajjangarh)',
    crowdLevel: 'High',
    weatherNow: { temp: 30, condition: 'Sunny', icon: '☀️' },
    nearbyHotels: [
      { name: 'Taj Lake Palace', price: 35000, rating: 4.9 },
      { name: 'Udai Kothi', price: 5000, rating: 4.5 },
      { name: 'BunkYard Hostel', price: 500, rating: 4.1 },
    ],
    localFood: ['Dal Baati', 'Gatte ki Sabzi', 'Malpua', 'Lassi'],
    travelTips: ['Boat ride on Lake Pichola at sunset', 'Watch folk dance at Bagore Ki Haveli', 'Explore the old city on foot'],
    lat: 24.5854,
    lng: 73.7125,
  },
  {
    id: 'd12',
    name: 'Andaman Islands',
    state: 'Andaman & Nicobar',
    category: 'beaches',
    tags: ['beaches', 'adventure'],
    images: [
      'https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&h=400&fit=crop',
    ],
    rating: 4.8,
    reviews: 5400,
    entryFee: '₹50 (Cellular Jail), Scuba from ₹3500',
    crowdLevel: 'Low',
    weatherNow: { temp: 29, condition: 'Tropical', icon: '🌴' },
    nearbyHotels: [
      { name: 'Taj Exotica', price: 15000, rating: 4.7 },
      { name: 'SeaShell Havelock', price: 6000, rating: 4.4 },
      { name: 'Barefoot Hostel', price: 800, rating: 4.0 },
    ],
    localFood: ['Grilled Lobster', 'Fish Curry', 'Coconut Prawn', 'Chilli Crab'],
    travelTips: ['Radhanagar Beach is Asia\'s best.', 'Book ferries to Havelock in advance', 'Scuba at Neil Island for beginners'],
    lat: 11.7401,
    lng: 92.6586,
  },
];

export const MOCK_MESSAGES = [
  { id: 'm1', sender: 'user', text: 'What is the best bus route from Jaipur to Udaipur?', timestamp: '2025-03-10T10:30:00Z' },
  { id: 'm2', sender: 'ai', text: 'Great question! 🚌 The best bus route from Jaipur to Udaipur is via NH-48. RSRTC Volvo buses run daily at 6:00 AM, 10:00 AM, and 10:30 PM. The journey takes about 6-7 hours. I recommend the overnight Volvo sleeper for comfort. Tickets start at ₹800. Want me to help plan your Udaipur itinerary?', timestamp: '2025-03-10T10:30:02Z' },
  { id: 'm3', sender: 'user', text: 'Yes! Also, any festivals in Udaipur in March?', timestamp: '2025-03-10T10:31:00Z' },
  { id: 'm4', sender: 'ai', text: 'Absolutely! 🎉 In March, Udaipur celebrates Mewar Festival (around Gangaur). Expect beautiful processions, folk dances, and fireworks at City Palace. The city will be more crowded than usual, so book hotels early. Shall I add this to your trip plan?', timestamp: '2025-03-10T10:31:02Z' },
  { id: 'm5', sender: 'user', text: 'That sounds amazing! Please add it.', timestamp: '2025-03-10T10:32:00Z' },
];

export const MOCK_ITINERARY = {
  id: 'trip1',
  title: 'Royal Rajasthan Explorer',
  state: 'Rajasthan',
  startDate: '2025-11-15',
  endDate: '2025-11-17',
  totalBudget: 15000,
  spent: 8500,
  days: [
    {
      date: '2025-11-15',
      label: 'Day 1 — Jaipur',
      weather: { temp: 28, condition: 'Sunny', icon: '☀️' },
      slots: [
        { time: '06:00 AM', place: 'Amer Fort', activity: 'Heritage Walk & Light Show', duration: '3 hours', cost: 500, type: 'sightseeing', tip: 'Reach by 6 AM to avoid tourist rush. The elephant ride is overrated—walk up instead!' },
        { time: '10:00 AM', place: 'Hawa Mahal', activity: 'Photography & Architecture Tour', duration: '1.5 hours', cost: 50, type: 'sightseeing', tip: 'Best photos from the cafe across the street, not from inside.' },
        { time: '12:30 PM', place: 'Johari Bazaar', activity: 'Street Food Trail', duration: '2 hours', cost: 300, type: 'food', tip: 'Try Rawat Mishthan for the legendary pyaaz kachori.' },
        { time: '04:00 PM', place: 'Nahargarh Fort', activity: 'Sunset Viewpoint', duration: '2 hours', cost: 200, type: 'sightseeing', tip: 'The Padao restaurant inside has the best sunset views of the city.' },
        { time: '07:30 PM', place: 'Chokhi Dhani', activity: 'Rajasthani Cultural Dinner', duration: '3 hours', cost: 1500, type: 'food', tip: 'Full traditional Rajasthani thali with folk dance performances.' },
      ],
    },
    {
      date: '2025-11-16',
      label: 'Day 2 — Pushkar',
      weather: { temp: 26, condition: 'Clear', icon: '🌤️' },
      slots: [
        { time: '05:30 AM', place: 'Pushkar Lake', activity: 'Sunrise at Brahma Ghat', duration: '1.5 hours', cost: 0, type: 'spiritual', tip: 'Remove shoes before approaching the ghats. Beware of unofficial priests asking for donations.' },
        { time: '08:00 AM', place: 'Brahma Temple', activity: 'One of the rare Brahma temples in the world', duration: '1 hour', cost: 0, type: 'temples', tip: 'One of the few temples dedicated to Lord Brahma—photographing inside is not allowed.' },
        { time: '10:00 AM', place: 'Pushkar Mela Ground', activity: 'Camel Fair Experience', duration: '3 hours', cost: 200, type: 'culture', tip: 'Bargain hard if buying handicrafts. The camel decoration competition is unmissable!' },
        { time: '02:00 PM', place: 'Sunset Cafe', activity: 'Rooftop Lunch & Lake View', duration: '2 hours', cost: 400, type: 'food', tip: 'Pushkar is a vegetarian town—no meat or eggs available anywhere.' },
        { time: '05:00 PM', place: 'Savitri Temple', activity: 'Ropeway Ride & Hilltop Temple', duration: '2 hours', cost: 150, type: 'adventure', tip: 'Take the ropeway up, walk down for panoramic views of the desert.' },
      ],
    },
    {
      date: '2025-11-17',
      label: 'Day 3 — Udaipur',
      weather: { temp: 27, condition: 'Partly Cloudy', icon: '⛅' },
      slots: [
        { time: '07:00 AM', place: 'Lake Pichola', activity: 'Morning Boat Ride', duration: '1.5 hours', cost: 400, type: 'sightseeing', tip: 'The government boat is cheaper than private ones and covers all islands.' },
        { time: '09:30 AM', place: 'City Palace', activity: 'Royal Heritage Tour', duration: '3 hours', cost: 300, type: 'historical', tip: 'Audio guide is worth ₹200 extra—covers stories not in guidebooks.' },
        { time: '01:00 PM', place: 'Ambrai Ghat', activity: 'Lakeside Lunch', duration: '1.5 hours', cost: 600, type: 'food', tip: 'Best view of Lake Palace from Ambrai restaurant. Book a table by the water.' },
        { time: '03:30 PM', place: 'Bagore Ki Haveli', activity: 'Folk Dance Performance', duration: '2 hours', cost: 150, type: 'culture', tip: 'Evening shows at 7 PM are the best—arrive early for front seats.' },
        { time: '06:00 PM', place: 'Sajjangarh Palace', activity: 'Monsoon Palace Sunset', duration: '1.5 hours', cost: 200, type: 'sightseeing', tip: 'The road up is steep—take an auto. Stunning 360° view of Udaipur at sunset.' },
      ],
    },
  ],
  budget: {
    total: 15000,
    spent: 8500,
    hotel: 4000,
    food: 2800,
    transport: 1500,
    activities: 2150,
    shopping: 1050,
    remaining: 3500,
  },
};

export const CHATBOT_RESPONSE_MAP = {
  bus: 'Great question about buses! 🚌 Major operators like RSRTC, KSRTC, and APSRTC connect most Indian cities. Use RedBus or IRCTC for online booking. Volvo AC buses cost ₹800-2000 for intercity routes. What route are you planning?',
  train: 'For train info! 🚂 Use IRCTC (irctc.co.in) to book. Tatkal booking opens at 10 AM (AC) and 11 AM (Sleeper). Popular trains: Rajdhani (fastest), Shatabdi (day travel), Garib Rath (budget AC). Which route do you need?',
  medical: 'For medical emergencies! 🏥 Dial 108 for ambulance services (free in most states). Major hospital chains: Apollo, Fortis, AIIMS. Always carry a basic first-aid kit while traveling. Pharmacies are available in all towns. Need help finding a hospital nearby?',
  hotel: 'Hotel help coming up! 🏨 Budget: Zostel/Hostelworld (₹500-1000), Mid: OYO/Treebo (₹1500-3000), Premium: Taj/ITC (₹8000+). Book via MakeMyTrip for best deals. What\'s your budget range and destination?',
  lost: 'Don\'t worry, I\'m here to help! 📍 Steps: 1) Share your Google Maps location 2) Note nearby landmarks 3) Ask locals for the nearest police station 4) Dial 112 for emergency help 5) Tourist helpline: 1800-111-363 (toll-free). Can you tell me which city you\'re in?',
  festival: 'Festival info coming up! 🎉 India has 30+ major festivals yearly! Upcoming ones include Pushkar Mela (Nov), Hornbill Festival (Dec), and Rann Utsav (Nov-Feb). Each brings unique experiences, food, and culture. Which region\'s festivals interest you?',
  food: 'Food guide ready! 🍛 India\'s culinary map is incredible! North: Butter Chicken, Chole Bhature | South: Dosa, Hyderabadi Biryani | East: Momos, Rasgulla | West: Vada Pav, Dhokla. Every state has unique flavors. Which cuisine are you curious about?',
  weather: 'Weather planning! 🌤️ India has 3 seasons: Summer (Mar-Jun), Monsoon (Jul-Sep), Winter (Oct-Feb). Best travel: Oct-Mar for most destinations. Hills are great Jun-Sep. Carry layers for North India winters. Which destination\'s weather do you need?',
  default: 'Namaste! 🙏 I\'m YatrAI, your AI travel buddy for India! I can help with:\n\n🚌 Bus & Train routes\n🏨 Hotel recommendations\n🎉 Festival calendars\n🍛 Food guides\n📍 Navigation help\n🌤️ Weather updates\n\nJust ask me anything about traveling in India!',
};

export const QUICK_REPLIES = [
  { id: 'qr1', text: '🚌 Bus Routes', keyword: 'bus' },
  { id: 'qr2', text: '🚂 Train Info', keyword: 'train' },
  { id: 'qr3', text: '🏥 Medical Help', keyword: 'medical' },
  { id: 'qr4', text: '🏨 Hotel SOS', keyword: 'hotel' },
  { id: 'qr5', text: '📍 Lost? Help me', keyword: 'lost' },
  { id: 'qr6', text: '🎉 Festivals', keyword: 'festival' },
];
